var GAME_LEVELS = [
  ["                                                                                ",
   "          vv                                                                    ",
   "                                                   o                             ",
   "       vv              oooo                                                     ",
   "                      xxxxxxx                                                   ",
   "                                                                                ",
   "                                   xxx            xxx             xxx           ",
   "                                  xx!xx          xx!xx           xx!xx          ",
   "                                  x!!!x xxx      x!!!x           x!!!x          ",
   "                                  xx!xx          xx!xx           xx!xx          ",
   "                                   xvx            xvx             xvx           ",
   "                                          xxxxx                              x  ",
   "  xxxx                                                                      x  ",
   "  x                     o                                                    x  ",
   "  x                                   xxx   o      ^        o              o x  ",
   "  x                     o                         xxx                        x  ",
   "  x  @         ^              xxxxx             xxxxxxx   xxxxxx             x  ",
   "  xxxxxxxxxxxxxxxxx**xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxx x",
   "                                                                    xxxxxxx     ",
   "                                                                                ",
   "                 xxxxx       xxxxxxx      xxxx     xxxxxxxxxxx                  ",
   "                        xxx          xxxxxxx   xxx             xxx              ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                        v       v    v                                                                            ",
   "          oo                                                                                                      ",
   "          xxx                                                                                                     ",
   "   o                                                                     o                                        ",
   "  xxx                                                                                                             ",
   "                               xxx                                   xxxxxxxx                                     ",
   "     xxx                      x   x                                                                               ",
   "             o               x     x                         xxxx                                                 ",
   "            xxx             x       xxx      ^                               xxx                                  ",
   "                           x           xxxxxxxxxxxxx    x                                o                        ",
   "     xxxx                 x                         x   x                              xxxx                       ",
   "                       ***                          x   x                                                         ",
   "                      x                             xx  x                                                         ",
   "           xx        x                              x   x                          o                              ",
   "                    x                               x   x                         xx                             ",
   "     @             x            xxxxx                  xx                                                         ",
   "    xxx  x   xxxxxx                                     x                                                         ",
   "    x x    xxx        xxxxx                             x                                                         ",
   "!!!!x x!!!!!!x                            xxxxxxxx  x   x                                                         ",
   "!!!!x x!!!!!!x                                      x   x                                                         ",
   "!!!!x x!!!!!!x                                      xx  x                                                         ",
   "!!!!x x!!!!!!x                                      x   x                                                         ",
   "!!!!x x!!!!!!x                                      x   x                                                         ",
   "!!!!x x!!!!!!x                                      x   x                                                         ",
   "!!!!x x!!!!!!x                                      x!!!x !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                oo                                                            ",
   "                                               xxxxx                                                          ",
   "                                                vvv      o                                                    ",
   "                                                        xxxxx       ooo                                       ",
   "                                                                   xxxxxx                                     ",
   "                                                                                   o                          ",
   "                                                                               xxxxxxx                        ",
   "                                                                                                              ",
   "                                                  @                                                           ",
   "                                                  x                    xx*xxx                                 ",
   "                                                               ooo                  xxx***                    ",
   "                                               x     x      xxxxxxxx                                          ",
   "                                                  x                                                           ",
   "                                               x     x                                                        ",
   "                                           x      x     x                                                     ",
   "                                                                                  vvvvvvvvvvvvvvvvvv          ",
   "                                        x       x      x     x                                                ",
   "                                                    ^                                                         ",
   "                                   x        x       x      x      x                                           ",
   "                                                                                                              ",
   "                             x          x       x       x     x        x                                      ",
   "                                                                                                              ",
   "  x                     x           x         x      x       x       x        x                               ",
   "  x                                                                                xxxxx                   x  ",
   "  x                    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    o   !!!!!!!!!!!!!!!!!!!!                       xxxx  ",
   "  x                vvv                            vvv               vvv        vvvv                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                      o                                        xxxx     x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                    xxx x  ",
   "  x                                                          ^                                             x  ",
   "  x               ooooooo        ^^^^             ooo               ooo          o                         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
